
modLoader="javafml" 
loaderVersion="[35,)" 
license="All rights reserved"

[[mods]] 
modId="wickerwingsmod"
version="0.0.1"
displayName="Wicker Wings" 
logoFile="wings.png"
credits=""
authors=""
description='''\

'''
